# Pandas Series and DataFrames

In [3]:
import pandas as pd
import numpy as np

## Pandas Series

### Create Pandas Series

In [4]:
# Create series: pass in a list
students = ['Alice', 'Jack', 'Molly']
print(pd.Series(students))

0    Alice
1     Jack
2    Molly
dtype: str

In [5]:
numbers = [1, 2, 3]
print(pd.Series(numbers))

0    1
1    2
2    3
dtype: int64

### Missing values in Pandas Series

In [6]:
# How does pandas handle missing data for str dtype series?
# Starting from pandas 3.0, str type is enabled by default
students = ['Alice', 'Jack', None]
print(pd.Series(students))

0    Alice
1     Jack
2      NaN
dtype: str

In [7]:
# How does pandas handle missing data for numerical series?
numbers = [1, 2, None]
print(pd.Series(numbers))

0    1.0
1    2.0
2    NaN
dtype: float64

In [8]:
# Equality checks on missing values np.nan do not work
print(np.nan == np.nan)
print(np.nan == None)
print(None == None)

False
False
True

In [9]:
# Instead, use isnan() to test missing values
print(np.isnan(np.nan))

True

### Create Pandas Series with Index

In [10]:
students_scores = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English'}
s = pd.Series(students_scores)
print(s)
print(s.index)

Alice      Physics
Jack     Chemistry
Molly      English
dtype: str
Index(['Alice', 'Jack', 'Molly'], dtype='str')

In [11]:
# Separate index creation from the data
s = pd.Series(['Physics', 'Chemistry', 'English'], index=['Alice', 'Jack', 'Molly'])
print(s)
print(s.index)

Alice      Physics
Jack     Chemistry
Molly      English
dtype: str
Index(['Alice', 'Jack', 'Molly'], dtype='str')

In [12]:
# When index do not align with the dictionary keys
# The unaligned index will contain a missing value
students_scores = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English'}
s = pd.Series(students_scores, index=['Alice', 'Molly', 'Sam'])
print(s)

Alice    Physics
Molly    English
Sam          NaN
dtype: str

### Query Pandas Series

In [13]:
students_classes = {'Alice': 'Physics',
                    'Jack': 'Chemistry',
                    'Molly': 'English',
                    'Sam': 'History'}
s = pd.Series(students_classes)
s

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: str

In [14]:
# iloc and loc: they are attributes, not methods. So use square brackets, not parentheses.

# use iloc to query the value of the forth entry
print(s.iloc[3])

# use iloc to query the value to the key 'Molly'
print(s.loc['Molly'])

# Pandas will behave as if iloc is used, when an integer parameter is passed in: e.g. s[3], s['Molly']
print(s['Molly'])

# However, Pandas can't determine automatically whether you're intending to query
# by index poistion or index label, if your index label is numeric.
# So the safer option is to be more explicit and use iloc or loc attributes directly.

History
English
English

In [15]:
# Two methods to aggregate a series
grades = pd.Series([90, 80, 70, 60])

# method 1: iterate over the series, sum, and divide
total = 0
for grade in grades:
    total += grade
print(total/len(grades))

# method 2: use numpy sum()
# Recommended: the numpy function utilizes parallel computing features.
import numpy as np
total = np.sum(grades)
print(total/len(grades))

75.0
75.0

In [16]:
numbers = pd.Series(np.random.randint(0, 1000,10000))

In [17]:
# Related feature: broadcasting - apply operations to every value in the series.
# e.g., we could use += operator directly on the Series object
numbers = pd.Series(np.random.randint(0, 1000,10000))
print(numbers.head())

numbers += 2
print(numbers.head())

0    587
1    420
2    533
3    837
4    370
dtype: int32
0    589
1    422
2    535
3    839
4    372
dtype: int32

In [18]:
# The .loc attribute lets you not only to modify data in place, but also add new data as well.
# If the value you pass to index doesn't exist, then a new entry is added.
s = pd.Series([1, 2, 3])

# let's add some new value
s.loc['History'] = 102
print(s)

0            1
1            2
2            3
History    102
dtype: int64

In [19]:
# Pandas with not unique index values
students_classes = pd.Series({'Alice': 'Physics',
                    'Jack': 'Chemistry',
                    'Molly': 'English',
                    'Sam': 'History'})
print(students_classes)
print()

kelly_classes = pd.Series(['Philosophy', 'Arts', 'Math'], index=['Kelly', 'Kelly', 'Kelly'])
print(kelly_classes)

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: str

Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: str

In [20]:
# Concat the two series
all_students_classes = pd.concat([students_classes, kelly_classes])
all_students_classes

Alice       Physics
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: str

## Dataframes

### Creating Dataframes

In [21]:
import pandas as pd
# method 1 to create a dataframe: list of series (each series is a row)
record1 = pd.Series({'Name':'Alice',
                     'Class':'Physics',
                     'Score': 85})
record2 = pd.Series({'Name':'Jack',
                     'Class':'Chemistry',
                     'Score': 82})
record3 = pd.Series({'Name':'Helen',
                     'Class':'Biology',
                     'Score': 90})
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school1'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [22]:
# Method 2 to create a dataframe: list of dictionaries (each is a row)
students = [{'Name':'Alice',
             'Class':'Physics',
             'Score': 85},
            {'Name':'Jack',
             'Class':'Chemistry',
             'Score': 82},
            {'Name':'Helen',
             'Class':'Biology',
             'Score': 90}]
df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])
print(df)

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

### Query the dataframe rows and columns

In [23]:
# query by index name
df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [24]:
# Since school1 correspondes to multiple records, the .loc will return a new dataframe
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [25]:
# select based on row and columns
df.loc['school1', 'Name']

school1    Alice
school1    Helen
Name: Name, dtype: str

In [26]:
# to get a column - method 1: transpose
df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [27]:
# to get a column - method 2: df[]
print(df['Name'])

# a single column  projection is a Series object
print(type(df['Name']))

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: str
<class 'pandas.Series'>

In [28]:
# select by both rows and columns - method 1: chaining
df.loc['school1']['Name']

school1    Alice
school1    Helen
Name: Name, dtype: str

In [29]:
# select by both rows and columns - method 2: use .loc
df.loc[:, ['Name', 'Score']]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

### Sort Values

In [31]:
df.sort_values(by=['Score'], ascending=True)

          Name      Class  Score
school2   Jack  Chemistry     82
school1  Alice    Physics     85
school1  Helen    Biology     90

### Dropping data

In [15]:
# Dropping data without overwriting - drop a row by index
print(df.drop('school1'))
print("---------------------------------------------------")

# Dropping data without overwriting - drop a column
# axis = 1 means dropping a column
print(df.drop('Name', axis=1))
print("---------------------------------------------------")

# Dropping data with overwriting
copy_df = df.copy()
copy_df.drop('Name', inplace=True, axis=1)
print(copy_df)
print("---------------------------------------------------")

# Dropping data with overwriting - use del
copy_df = df.copy()
del copy_df['Class']
print(copy_df)

         Name      Class  Score
school2  Jack  Chemistry     82
---------------------------------------------------
             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90
---------------------------------------------------
             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90
---------------------------------------------------
          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

### Indexing and Loading

In [18]:
# Load data and set the first column as index
df = pd.read_csv('data_intro/Admission_Predict.csv', index_col = 0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

### Clean/Rename Column Names

In [19]:
# Check columns
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='str')

In [20]:
# Clean (If needed) columns names - strip leading/trailing spaces
new_df = df.rename(mapper=str.strip, axis='columns')
new_df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='str')

In [21]:
# rename column names:
new_df = new_df.rename(columns={'LOR': 'Letter of Recommendation'})
new_df.head()

,GRE Score,TOEFL Score,University Rating,SOP,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [23]:
# change all values in columns to lower case
cols = list(df.columns)
cols = [x.lower().strip() for x in cols]
df.columns = cols
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

### Subsetting dataframes

In [26]:
df = pd.read_csv('data_intro/Admission_Predict.csv', index_col = 0)
df.columns = [x.lower().strip() for x in cols]
df

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...
396,324,110,3,3.5,3.5,9.04,1,0.82
397,325,107,3,3.0,3.5,9.11,1,0.84
398,330,116,4,5.0,4.5,9.45,1,0.91
399,312,103,3,3.5,4.0,8.78,0,0.67
400,333,117,4,5.0,4.0,9.66,1,0.95

In [27]:
# use Boolean masks
admit_mask = df['chance of admit'] > 0.7
admit_mask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398     True
399    False
400     True
Name: chance of admit, Length: 400, dtype: bool

In [28]:
# use the .where() on the original dataframe
# However, all of the rows which did not meet the condition have NaN data instead, they are not dropped.
df.where(admit_mask).head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# use dropna() to drop the NaN
df.where(admit_mask).dropna().head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [30]:
# More common: shorthand syntex
df[df['chance of admit']>0.7].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90

In [32]:
# If multiple conditions, use () to separate
mask = (df['chance of admit']>0.7) & (df['chance of admit']<0.9)
df[mask].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
7,321,109,3,3.0,4.0,8.20,1,0.75
12,327,111,4,4.0,4.5,9.00,1,0.84

### Change Index

In [33]:
import pandas as pd
df = pd.read_csv("data_intro/Admission_Predict.csv", index_col=0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [34]:
# copy the index into its own column
df['Serial Number'] = df.index

# set the index by another column
df = df.set_index('Chance of Admit ')
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
Chance of Admit,,,,,,,,
0.92,337,118,4,4.5,4.5,9.65,1,1
0.76,324,107,4,4.0,4.5,8.87,1,2
0.72,316,104,3,3.0,3.5,8.00,1,3
0.80,322,110,3,3.5,2.5,8.67,1,4
0.65,314,103,2,2.0,3.0,8.21,0,5

In [36]:
# to get rid of the index, call function reset_index()
df = df.reset_index()
df.head()

,Chance of Admit,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
0,0.92,337,118,4,4.5,4.5,9.65,1,1
1,0.76,324,107,4,4.0,4.5,8.87,1,2
2,0.72,316,104,3,3.0,3.5,8.00,1,3
3,0.80,322,110,3,3.5,2.5,8.67,1,4
4,0.65,314,103,2,2.0,3.0,8.21,0,5

In [38]:
# multi-level indexing - simply give it a list of columns that we're interested in promoting to an index.
df = pd.read_csv("data_intro/census.csv")
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [39]:
# check the sum level, 40 is at the state level, 50 is at county level
df['SUMLEV'].unique()

array([40, 50])

In [40]:
df = df[df['SUMLEV']==50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [41]:
columns_to_keep = ['STNAME','CTYNAME','BIRTHS2010','BIRTHS2011','BIRTHS2012','BIRTHS2013',
                   'BIRTHS2014','BIRTHS2015','POPESTIMATE2010','POPESTIMATE2011',
                   'POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

,STNAME,CTYNAME,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,636,615,574,623,600,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,2187,2092,2160,2186,2240,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,335,300,283,260,269,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,266,245,259,247,253,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,744,710,646,618,603,57373,57711,57776,57734,57658,57673

In [42]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

                        BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME
Alabama Autauga County         151         636         615         574
        Baldwin County         517        2187        2092        2160
        Barbour County          70         335         300         283
        Bibb County             44         266         245         259
        Blount County          183         744         710         646

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County         623         600            54660
        Baldwin County        2186        2240           183193
        Barbour County         260         269            27341
        Bibb County            247         253            22861
        Blount County          618         603            57373

                        POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME
Alabama Autauga County            55253            55175            55038
        Baldwin County           186659           190396           195126
        Barbour County            27226            27159            26973
        Bibb County               22733            22642            22512
        Blount County             57711            57776            57734

                        POPESTIMATE2014  POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County            55290            55347
        Baldwin County           199713           203709
        Barbour County            26815            26489
        Bibb County               22549            22583
        Blount County             57658            57673

In [43]:
# Query according to the level of index
df.loc['Michigan', 'Washtenaw County']

BIRTHS2010            977
BIRTHS2011           3826
BIRTHS2012           3780
BIRTHS2013           3662
BIRTHS2014           3683
BIRTHS2015           3709
POPESTIMATE2010    345563
POPESTIMATE2011    349048
POPESTIMATE2012    351213
POPESTIMATE2013    354289
POPESTIMATE2014    357029
POPESTIMATE2015    358880
Name: (Michigan, Washtenaw County), dtype: int64

In [44]:
# query with two index locations for a double layer index, pass in two tupes
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

                           BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME   CTYNAME
Michigan Washtenaw County         977        3826        3780        3662
         Wayne County            5918       23819       23270       23377

                           BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME   CTYNAME
Michigan Washtenaw County        3683        3709           345563
         Wayne County           23607       23586          1815199

                           POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME   CTYNAME
Michigan Washtenaw County           349048           351213           354289
         Wayne County              1801273          1792514          1775713

                           POPESTIMATE2014  POPESTIMATE2015
STNAME   CTYNAME
Michigan Washtenaw County           357029           358880
         Wayne County              1766008          1759335