# Pandas Pivot Tables

In [1]:
import pandas as pd
import numpy as np

A pivot table is itself a DataFrame, where the rows represent one variable that you're interested in, the columns another, and the cell's some aggregate value. A pivot table also tends to includes marginal values as well, which are the sums for each column and row.

In [3]:
# Load the Times Higher Education World University Ranking dataset
df = pd.read_csv('data_intro/cwurData.csv')
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012

In [6]:
# We are interested in creating a tier level based on world ranks
def create_category(ranking):
    # Since the rank is just an integer, I'll just do a bunch of if/elif statements
    if (ranking >= 1) & (ranking <= 100):
        return "First Tier Top Unversity"
    elif (ranking >= 101) & (ranking <= 200):
        return "Second Tier Top Unversity"
    elif (ranking >= 201) & (ranking <= 300):
        return "Third Tier Top Unversity"
    return "Other Top Unversity"

# Apply this to the world_rank column
df['Rank_Level'] = df['world_rank'].apply(lambda x: create_category(x))
df1 = df[['Rank_Level', 'institution', 'country', 'score', 'year']]
df1.head()

,Rank_Level,institution,country,score,year
0,First Tier Top Unversity,Harvard University,USA,100.00,2012
1,First Tier Top Unversity,Massachusetts Institute of Technology,USA,91.67,2012
2,First Tier Top Unversity,Stanford University,USA,89.50,2012
3,First Tier Top Unversity,University of Cambridge,United Kingdom,86.17,2012
4,First Tier Top Unversity,California Institute of Technology,USA,85.21,2012

In [17]:
# Use a pivot_table to find that for each country, what are the average scores for each tier
df1.pivot_table(values='score', index='country', columns='Rank_Level',
                aggfunc=[np.mean]).head()

                               mean                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN           44.672857
Australia                   47.9425           44.645750
Austria                         NaN           44.864286
Belgium                     51.8750           45.081000
Brazil                          NaN           44.499706


Rank_Level Second Tier Top Unversity Third Tier Top Unversity
country
Argentina                        NaN                      NaN
Australia                    49.2425                47.285000
Austria                          NaN                47.066667
Belgium                      49.0840                46.746667
Brazil                       49.5650                      NaN

In [18]:
# Find that for each country, what are the average and max scores for each tier
df1.pivot_table(values='score', index='country', columns='Rank_Level',
                aggfunc=[np.mean, np.max]).head()

                               mean                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN           44.672857
Australia                   47.9425           44.645750
Austria                         NaN           44.864286
Belgium                     51.8750           45.081000
Brazil                          NaN           44.499706

                                                               \
Rank_Level Second Tier Top Unversity Third Tier Top Unversity
country
Argentina                        NaN                      NaN
Australia                    49.2425                47.285000
Austria                          NaN                47.066667
Belgium                      49.0840                46.746667
Brazil                       49.5650                      NaN

                                max                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN               45.66
Australia                     51.61               45.97
Austria                         NaN               46.29
Belgium                       52.03               46.21
Brazil                          NaN               46.08


Rank_Level Second Tier Top Unversity Third Tier Top Unversity
country
Argentina                        NaN                      NaN
Australia                      50.40                    47.47
Austria                          NaN                    47.78
Belgium                        49.73                    47.14
Brazil                         49.82                      NaN

In [22]:
# Add margins (i.e., total averages, and total max)
df2 = df1.pivot_table(values='score', index='country', columns='Rank_Level',
                      aggfunc=[np.mean, np.max],
                      margins=True)
df2.head()

                               mean                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN           44.672857
Australia                   47.9425           44.645750
Austria                         NaN           44.864286
Belgium                     51.8750           45.081000
Brazil                          NaN           44.499706

                                                                          \
Rank_Level Second Tier Top Unversity Third Tier Top Unversity        All
country
Argentina                        NaN                      NaN  44.672857
Australia                    49.2425                47.285000  45.825517
Austria                          NaN                47.066667  45.139583
Belgium                      49.0840                46.746667  47.011000
Brazil                       49.5650                      NaN  44.781111

                                max                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN               45.66
Australia                     51.61               45.97
Austria                         NaN               46.29
Belgium                       52.03               46.21
Brazil                          NaN               46.08


Rank_Level Second Tier Top Unversity Third Tier Top Unversity    All
country
Argentina                        NaN                      NaN  45.66
Australia                      50.40                    47.47  51.61
Austria                          NaN                    47.78  47.78
Belgium                        49.73                    47.14  52.03
Brazil                         49.82                      NaN  49.82

In [24]:
# access the index and columns of a pivot table (which is essentially multi-level dataframe)
print(df2.index)
print("----------------------------")
print(df2.columns)

Index(['Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria',
       'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Egypt', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Iran',
       'Ireland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Lithuania',
       'Malaysia', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Portugal', 'Puerto Rico', 'Romania', 'Russia', 'Saudi Arabia',
       'Serbia', 'Singapore', 'Slovak Republic', 'Slovenia', 'South Africa',
       'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand',
       'Turkey', 'USA', 'Uganda', 'United Arab Emirates', 'United Kingdom',
       'Uruguay', 'All'],
      dtype='str', name='country')
----------------------------
MultiIndex([('mean',  'First Tier Top Unversity'),
            ('mean',       'Other Top Unversity'),
            ('mean', 'Second Tier Top Unversity'),
            ('mean',  'Third Tier Top Unversity'),
            ('mean',                       'All'),
            ( 'max',  'First Tier Top Unversity'),
            ( 'max',       'Other Top Unversity'),
            ( 'max', 'Second Tier Top Unversity'),
            ( 'max',  'Third Tier Top Unversity'),
            ( 'max',                       'All')],
           names=[None, 'Rank_Level'])

In [27]:
# Query pivot table with chained reference
# The following query returns a series
df2['mean']['First Tier Top Unversity'].head()

country
Argentina        NaN
Australia    47.9425
Austria          NaN
Belgium      51.8750
Brazil           NaN
Name: First Tier Top Unversity, dtype: float64

In [28]:
# Find which country has the maximum average score on first tier university level?
df2['mean']['First Tier Top Unversity'].idxmax()

'United Kingdom'

In [31]:
# We can use stacking to move the multi-layer index to the row indices
df3=df2.stack()
df3.head(10)

                                          mean    max
country   Rank_Level
Argentina First Tier Top Unversity         NaN    NaN
          Other Top Unversity        44.672857  45.66
          Second Tier Top Unversity        NaN    NaN
          Third Tier Top Unversity         NaN    NaN
          All                        44.672857  45.66
Australia First Tier Top Unversity   47.942500  51.61
          Other Top Unversity        44.645750  45.97
          Second Tier Top Unversity  49.242500  50.40
          Third Tier Top Unversity   47.285000  47.47
          All                        45.825517  51.61

In [35]:
# we can also unstack to return to the previous df
df3.unstack().head()

                               mean                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN           44.672857
Australia                   47.9425           44.645750
Austria                         NaN           44.864286
Belgium                     51.8750           45.081000
Brazil                          NaN           44.499706

                                                                          \
Rank_Level Second Tier Top Unversity Third Tier Top Unversity        All
country
Argentina                        NaN                      NaN  44.672857
Australia                    49.2425                47.285000  45.825517
Austria                          NaN                47.066667  45.139583
Belgium                      49.0840                46.746667  47.011000
Brazil                       49.5650                      NaN  44.781111

                                max                      \
Rank_Level First Tier Top Unversity Other Top Unversity
country
Argentina                       NaN               45.66
Australia                     51.61               45.97
Austria                         NaN               46.29
Belgium                       52.03               46.21
Brazil                          NaN               46.08


Rank_Level Second Tier Top Unversity Third Tier Top Unversity    All
country
Argentina                        NaN                      NaN  45.66
Australia                      50.40                    47.47  51.61
Austria                          NaN                    47.78  47.78
Belgium                        49.73                    47.14  52.03
Brazil                         49.82                      NaN  49.82

In [36]:
# if unstack again:
df3.unstack().unstack()

      Rank_Level                country
mean  First Tier Top Unversity  Argentina                    NaN
                                Australia                47.9425
                                Austria                      NaN
                                Belgium                  51.8750
                                Brazil                       NaN
                                                          ...
max   All                       Uganda                   44.4000
                                United Arab Emirates     44.3600
                                United Kingdom           97.6400
                                Uruguay                  44.3500
                                All                     100.0000
Length: 600, dtype: float64

In [38]:
# We actually end up unstacking all the way to just a single column, so a series object is returned. This column is just a "value", the meaning of which is denoted by the heirarachical index of operation, rank, and country.