# Pandas Date and Time

Pandas has four main time related classes. **Timestamp**, **DatetimeIndex**, **Period**, and **PeriodIndex**.
- **Timestamp**: represents a single timestamp and associates values with points in time
- **DatetimeIndex**:  The index of a timestamp is DatetimeIndex
- **Period**: represents a single time span, such as a specific day or month.
- **PeriodIndex**: The index of a Period is PeriodIndex

In [1]:
import pandas as pd
import numpy as np

## Timestamp

In [2]:
# Timestamp is interchangeable with Python's datetime in most cases.
pd.Timestamp('9/1/2019 10:05AM')

Timestamp('2019-09-01 10:05:00')

In [12]:
# Create a timestamp by passing in year, month, date, hour, minute, second
timestp = pd.Timestamp(2026, 12, 20, 18, 6, 30)
timestp

Timestamp('2026-12-20 18:06:30')

In [13]:
# show the weekday of the timestamp, 1 represents Monday and 7 represents Sunday
timestp.isoweekday()

7

In [15]:
# extract year, month, day, hour, minute, second from a timestamp
print(timestp.year)
print(timestp.hour)
print(timestp.second)

2026
18
30

## Period

In [20]:
# Create a period that is January 2016,
pd.Period('1/2026')

Period('2026-01', 'M')

In [21]:
# Create a period that is Mar 5, 2016
pd.Period('3/5/2026')

Period('2026-03-05', 'D')

In [22]:
# Perform subtraction (i.e., back by 2 days)
pd.Period('3/5/2026') - 2

Period('2026-03-03', 'D')

## DatetimeIndex and PeriodIndex

In [28]:
# Create a Series with timestamp index --> a DatetimeIndex
t1 = pd.Series(list('abc'), index = [pd.Timestamp('2016-09-01'),
                                     pd.Timestamp('2016-09-02'), pd.Timestamp('2016-09-03')])
t1

2016-09-01    a
2016-09-02    b
2016-09-03    c
dtype: str

In [27]:
type(t1.index)

pandas.DatetimeIndex

In [29]:
# Similarly, we can create a period-based index as well.
t2 = pd.Series(list('def'), [pd.Period('2016-09'), pd.Period('2016-10'),
                             pd.Period('2016-11')])
t2

2016-09    d
2016-10    e
2016-11    f
Freq: M, dtype: str

In [30]:
type(t2.index)

pandas.PeriodIndex

## Converting to Datetime

In [31]:
# Now, let's look into how to convert to Datetime. Suppose we have a list of dates as strings and we want to
# create a new dataframe

# I'm going to try a bunch of different date formats
d1 = ['2 June 2013', 'Aug 29, 2014', '2015-06-26', '7/12/16']

# And just some random data
ts3 = pd.DataFrame(np.random.randint(10, 100, (4,2)), index=d1,
                   columns=list('ab'))
ts3

               a   b
2 June 2013   33  87
Aug 29, 2014  72  99
2015-06-26    61  74
7/12/16       53  78

In [33]:
# Using pandas to_datetime, pandas will try to convert these to Datetime and put them in a standard format.

ts3.index = pd.to_datetime(ts3.index, format='mixed')
ts3

             a   b
2013-06-02  33  87
2014-08-29  72  99
2015-06-26  61  74
2016-07-12  53  78

In [34]:
# to_datetime also() has options to change the date parse order. For example, we
# can pass in the argument dayfirst = True to parse the date in European date.

pd.to_datetime('4.7.12', dayfirst=True)

Timestamp('2012-07-04 00:00:00')

## Timedelta (time differences)

In [35]:
# The difference between September 3rd and September 1st -> 2 days
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

In [40]:
# We can also do something like find what the date and time is for
# 12 days and three hours past September 2nd, at 8:10 AM.
pd.Timestamp('9/2/2026 8:10AM') + pd.Timedelta('12D 3h')

Timestamp('2026-09-14 11:10:00')

## Offset

Offset is similar to timedelta, but it follows specific calendar duration rules. Offset allows flexibility in terms of types of time intervals. Besides hour, day, week, month, etc it also has business day, end of month, semi month begin etc

In [41]:
# Let's create a timestamp, and see what day is that
pd.Timestamp('9/4/2016').weekday()

6

In [42]:
# Now we can now add the timestamp with a week ahead
pd.Timestamp('9/4/2016') + pd.offsets.Week()

Timestamp('2016-09-11 00:00:00')

In [43]:
# Now let's try to do the month end, then we would have the last day of Septemer
pd.Timestamp('9/4/2016') + pd.offsets.MonthEnd()

Timestamp('2016-09-30 00:00:00')

## Working with Dates in a Dataframe

In [49]:
# create an index of 9 dates, taken bi-weekly on every Sunday
pd.date_range('10-01-2026', periods=9, freq='2W-SUN')

DatetimeIndex(['2026-10-04', '2026-10-18', '2026-11-01', '2026-11-15',
               '2026-11-29', '2026-12-13', '2026-12-27', '2027-01-10',
               '2027-01-24'],
              dtype='datetime64[us]', freq='2W-SUN')

In [47]:
# create an index of 9 consecutive business days.
pd.date_range('10-01-2026', periods=9, freq='B')

DatetimeIndex(['2026-10-01', '2026-10-02', '2026-10-05', '2026-10-06',
               '2026-10-07', '2026-10-08', '2026-10-09', '2026-10-12',
               '2026-10-13'],
              dtype='datetime64[us]', freq='B')

In [50]:
# create an index of 12 days, increment by quarter, start in June (i.e., June 1)
pd.date_range('04-01-2026', periods=12, freq='QS-JUN')

DatetimeIndex(['2026-06-01', '2026-09-01', '2026-12-01', '2027-03-01',
               '2027-06-01', '2027-09-01', '2027-12-01', '2028-03-01',
               '2028-06-01', '2028-09-01', '2028-12-01', '2029-03-01'],
              dtype='datetime64[us]', freq='QS-JUN')

In [65]:
# Now, let's go back to our weekly on Sunday example and create a DataFrame using these dates, and some random data, and see what we can do with it.
dates = pd.date_range('10-01-2026', periods=9, freq='2W-SUN')
df = pd.DataFrame({'Count 1': 100 + np.random.randint(-5, 10, 9).cumsum(),
                  'Count 2': 120 + np.random.randint(-5, 10, 9)}, index=dates)
df

            Count 1  Count 2
2026-10-04       98      125
2026-10-18      105      123
2026-11-01      108      119
2026-11-15      111      124
2026-11-29      111      116
2026-12-13      110      122
2026-12-27      108      120
2027-01-10      114      128
2027-01-24      118      123

In [66]:
# check what day of the week a specific date is
# Note, Monday is 0, Sunday is 6.
df.index.weekday

Index([6, 6, 6, 6, 6, 6, 6, 6, 6], dtype='int32')

In [67]:
# We can also use diff() to find the difference between each date's value.
df.diff()

            Count 1  Count 2
2026-10-04      NaN      NaN
2026-10-18      7.0     -2.0
2026-11-01      3.0     -4.0
2026-11-15      3.0      5.0
2026-11-29      0.0     -8.0
2026-12-13     -1.0      6.0
2026-12-27     -2.0     -2.0
2027-01-10      6.0      8.0
2027-01-24      4.0     -5.0

In [69]:
# Suppose we want to know what the mean count is for each month in our DataFrame. We can do this using resample. Converting from a higher frequency from a lower frequency is called downsampling (we'll talk about this in a moment)
df.resample('ME').mean()

            Count 1     Count 2
2026-10-31    101.5  124.000000
2026-11-30    110.0  119.666667
2026-12-31    109.0  121.000000
2027-01-31    116.0  125.500000

In [84]:
# Now let's talk about datetime indexing and slicing, which is a wonderful feature of the pandas DataFrame.
print(df[df.index.year==2027])
print('------------------------------')
# A quicker way is to use partial string indexing (.loc[] is required in recent Pandas versions)
print(df.loc['2027'])

            Count 1  Count 2
2027-01-10      114      128
2027-01-24      118      123
------------------------------
            Count 1  Count 2
2027-01-10      114      128
2027-01-24      118      123

In [85]:
# partial indexing with year and month
print(df.loc['2026-12'])

            Count 1  Count 2
2026-12-13      110      122
2026-12-27      108      120

In [86]:
# slicing to get a range of dates
print(df.loc['2026-12':])

            Count 1  Count 2
2026-12-13      110      122
2026-12-27      108      120
2027-01-10      114      128
2027-01-24      118      123

In [87]:
df.loc['2026']

            Count 1  Count 2
2026-10-04       98      125
2026-10-18      105      123
2026-11-01      108      119
2026-11-15      111      124
2026-11-29      111      116
2026-12-13      110      122
2026-12-27      108      120